name: Build and Publish

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy-notify:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code 🛎
        uses: actions/checkout@v2
        with: 
          persist-credentials: false
      # Build the blog
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          echo "buzzword.engineering" > public/CNAME
        env: 
          PAT_USER: ${{ secrets.PAT_USER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true  
